AWSTemplateFormatVersion: 2010-09-09
Description: >-
  description here
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction


  # not sure if the name here really matters
  lambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/index.handler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      MemorySize: 128
      Timeout: 100
      Description: description
      Events:
        Example:
          Type: Api
          Properties:
            Path: /path/to/endpoint
            Method: GET
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - src/index.ts
        Banner:
        - js=import { createRequire } from 'module'; const require = createRequire(import.meta.url);
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON